version: '3.8'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    container_name: async_db

volumes:
  db:
    driver: local