version: '3.3'

services:

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - '5431:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
    container_name: async_db

