version: '3.8'

services:

  db:
    image: postgres:15.2-alpine
    container_name: async_db
    restart: always
    env_file:
      - .env
    volumes:
      - /var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: async_app
    ports:
      - '8080:8080'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
